spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/url_shortcut
    username: postgres
    password: password
  jpa:
    show-sql: true
logging:
  level:
    root: info
    ru.job4j: debug
