spring:
  config.name: Job4J URL Shortcut
  profiles.default: dev
  liquibase:
    contexts: ${spring.profiles.active}
    change-log: classpath:/db/changelog/000-changelog-main.yaml
  jpa.hibernate.ddl-auto: validate
