spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/url_shortcut
    username: postgres
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
  test:
    database:
      replace: none
logging:
  level:
    root: info
    ru.job4j: debug
