spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_DELAY=-1
    generate-unique-name: false
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
  test:
    database:
      replace: none
logging:
  level:
    root: info
    ru.job4j: debug
