package ru.job4j.urlshortcut.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import java.time.LocalDateTime;
import java.util.UUID;

/** Model class to transfer and store log information about {@code Url} redirections. */
@Entity
@Table(name = "url_access_log")
public class UrlAccessRecord {

    /** Unique identification number generated by persistent storage. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Target {@code Url} ID. */
    @Column(name = "url_uuid")
    private UUID urlUuid;

    /** Access timestamp. */
    private LocalDateTime timestamp;
}
